# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  app:
    image: labtoolsapi
    build:
      context: ./
      target: development
    depends_on:
      - db
    volumes: 
      - ../webconfig:/config
      - ~/.aws:/root/.aws

  db:
    image: postgres:latest
    ports:
      - 5432:5432
    restart: always
    volumes: 
      - db-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin1234"
      POSTGRES_DB: "labtools"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    restart: always
    volumes:
      - pgadmin:/root/.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin1234

volumes:
  db-data:
  pgadmin:
